runit: update urls, fix undeclared function errors
The existing `livecheck` block for `runit` checks the tarball link on
the install page (https://smarden.org/runit/install). The URL
redirects from http://smarden.org/runit/install.html to
https://smarden.org/runit/install.html and then to
https://smarden.org/runit/install. This updates the URL to avoid the
redirection.

The `homepage` similarly redirects from http://smarden.org/runit to
https://smarden.org/runit/ and the `stable` URL redirects from HTTP
to HTTPS, so this also updates those URLs.

This also adds a patch to resolve `call to undeclared function` errors
that appear on macOS due to not including `<unistd.h>`. For example:

```
lock_ex.c:12:30: error: call to undeclared function 'lockf'; ISO C99
and later do not support implicit function declarations
[-Wimplicit-function-declaration]
int lock_ex(int fd) { return lockf(fd,1,0); }
```